# .github/workflows/Part2.yml
name: Part 2 - Forecasting

on:
  workflow_run:
    workflows: ["Part_1_bis"]
    types:
      - completed
  workflow_dispatch:

jobs:
  forecasting:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      REPO: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install build-essential
          pip install -r requirements.txt
          pip install requests

      - name: Download artifact from Part_1
        run: |
          python .github/scripts/download_artifact_v2.py

      - name: Extract artifact
        run: |
          unzip intermediate-data_v2.zip -d Results/
          mv Results/Results/* Results/
          rmdir Results/Results

      - name: Run forecast
        run: python forecast.py

      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: Update file"
          add: "*.csv *.pkl"
