# .github/workflows/Part1.yml
name: Part_1

on:
  schedule:
    # Run monthly on the 1st at 00:00 UTC
    - cron: '0 0 25 * *'
  workflow_dispatch: 

jobs:
  data-processing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install build-essential
        pip install -r requirements.txt
        
    - name: Run data processing
      timeout-minutes: 350 
      continue-on-error: true
      run: python data_process.py
      
    - name: Upload intermediate results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: intermediate-data
        path: |
          Results/
          df_prio.csv
          *.pkl
        retention-days: 1
